gcc -o build/basic/computed.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/computed.c
gcc -o build/basic/computed.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/computed.c
gcc -o build/basic/count_and_size.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/count_and_size.c
gcc -o build/basic/count_and_size.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/count_and_size.c
gcc -o build/basic/gc.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/gc.c
gcc -o build/basic/gc.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/gc.c
gcc -o build/basic/hash.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/hash.c
gcc -o build/basic/hash.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/hash.c
gcc -o build/basic/memory.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/memory.c
gcc -o build/basic/memory.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/memory.c
gcc -o build/basic/multiply.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/multiply.c
gcc -o build/basic/multiply.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/multiply.c
gcc -o build/basic/nodes.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/nodes.c
gcc -o build/basic/nodes.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/nodes.c
gcc -o build/basic/partitions.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/partitions.c
gcc -o build/basic/partitions.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/partitions.c
gcc -o build/basic/references.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/references.c
gcc -o build/basic/references.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/references.c
gcc -o build/basic/replace.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/replace.c
gcc -o build/basic/replace.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/replace.c
gcc -o build/basic/shadows.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/shadows.c
gcc -o build/basic/shadows.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/shadows.c
gcc -o build/basic/sort.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/basic/sort.c
gcc -o build/basic/sort.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/basic/sort.c
gcc -o build/fnf/io.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/fnf/io.c
gcc -o build/fnf/io.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/fnf/io.c
gcc -o build/util.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/util.c
gcc -o build/verify.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/verify.c
gcc -o build/manager/copy.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/manager/copy.c
gcc -o build/manager/manager.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/manager/manager.c
gcc -o build/manager/interface.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/manager/interface.c
gcc -o build/manager/stats.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/manager/stats.c
gcc -o build/manager/variables.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/manager/variables.c
gcc -o build/vtree_operations/cartesian_product.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/cartesian_product.c
gcc -o build/vtree_operations/dissect.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/dissect.c
gcc -o build/vtree_operations/limits.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/limits.c
gcc -o build/vtree_operations/op_left_rotate.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/op_left_rotate.c
gcc -o build/vtree_operations/op_right_rotate.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/op_right_rotate.c
gcc -o build/vtree_operations/op_swap.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/op_swap.c
gcc -o build/vtree_operations/rollback.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/rollback.c
gcc -o build/vtree_operations/split.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_operations/split.c
gcc -o build/vtree_search/auto.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_search/auto.c
gcc -o build/vtree_search/search.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_search/search.c
gcc -o build/vtree_search/state.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_search/state.c
gcc -o build/vtrees/vtree.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/vtree.c
gcc -o build/vtrees/compare.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/compare.c
gcc -o build/vtrees/edit.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/edit.c
gcc -o build/vtrees/io.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/io.c
gcc -o build/vtrees/maps.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/maps.c
gcc -o build/vtrees/moves.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/moves.c
gcc -o build/vtrees/static.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtrees/static.c
gcc -o build/sdds/io.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/io.c
gcc -o build/sdds/apply.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/apply.c
gcc -o build/sdds/bits.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/bits.c
gcc -o build/sdds/cardinality.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/cardinality.c
gcc -o build/sdds/copy.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/copy.c
gcc -o build/sdds/count.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/count.c
gcc -o build/sdds/condition.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/condition.c
gcc -o build/sdds/essential_vars.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/essential_vars.c
gcc -o build/sdds/exists_multiple.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/exists_multiple.c
gcc -o build/sdds/exists_multiple_static.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/exists_multiple_static.c
gcc -o build/sdds/exists.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/exists.c
gcc -o build/sdds/forall.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/forall.c
gcc -o build/sdds/rename_vars.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/rename_vars.c
gcc -o build/sdds/model_count.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/model_count.c
gcc -o build/sdds/size.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/size.c
gcc -o build/sdds/wmc.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/sdds/wmc.c
gcc -o build/vtree_fragments/construction.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_fragments/construction.c
gcc -o build/vtree_fragments/moves.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_fragments/moves.c
gcc -o build/vtree_fragments/operations.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -Iinclude -Isrc src/vtree_fragments/operations.c
gcc -o build/version.o -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -DSDD_VERSION=\"2.0\" -DSDD_DATE=\"June\ 27,\ 2022\" -Iinclude -Isrc src/version.c
ar rc build/libsdd.a build/util.o build/verify.o build/fnf/io.o build/manager/copy.o build/manager/manager.o build/manager/interface.o build/manager/stats.o build/manager/variables.o build/vtree_operations/cartesian_product.o build/vtree_operations/dissect.o build/vtree_operations/limits.o build/vtree_operations/op_left_rotate.o build/vtree_operations/op_right_rotate.o build/vtree_operations/op_swap.o build/vtree_operations/rollback.o build/vtree_operations/split.o build/vtree_search/auto.o build/vtree_search/search.o build/vtree_search/state.o build/basic/computed.o build/basic/count_and_size.o build/basic/gc.o build/basic/hash.o build/basic/memory.o build/basic/multiply.o build/basic/nodes.o build/basic/partitions.o build/basic/references.o build/basic/replace.o build/basic/shadows.o build/basic/sort.o build/vtrees/vtree.o build/vtrees/compare.o build/vtrees/edit.o build/vtrees/io.o build/vtrees/maps.o build/vtrees/moves.o build/vtrees/static.o build/sdds/io.o build/sdds/apply.o build/sdds/bits.o build/sdds/cardinality.o build/sdds/copy.o build/sdds/count.o build/sdds/condition.o build/sdds/essential_vars.o build/sdds/exists_multiple.o build/sdds/exists_multiple_static.o build/sdds/exists.o build/sdds/forall.o build/sdds/rename_vars.o build/sdds/model_count.o build/sdds/size.o build/sdds/wmc.o build/vtree_fragments/construction.o build/vtree_fragments/moves.o build/vtree_fragments/operations.o build/version.o
ranlib build/libsdd.a
gcc -o build/util.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/util.c
gcc -o build/verify.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/verify.c
gcc -o build/manager/copy.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/manager/copy.c
gcc -o build/manager/manager.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/manager/manager.c
gcc -o build/manager/interface.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/manager/interface.c
gcc -o build/manager/stats.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/manager/stats.c
gcc -o build/manager/variables.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/manager/variables.c
gcc -o build/vtree_operations/cartesian_product.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/cartesian_product.c
gcc -o build/vtree_operations/dissect.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/dissect.c
gcc -o build/vtree_operations/limits.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/limits.c
gcc -o build/vtree_operations/op_left_rotate.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/op_left_rotate.c
gcc -o build/vtree_operations/op_right_rotate.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/op_right_rotate.c
gcc -o build/vtree_operations/op_swap.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/op_swap.c
gcc -o build/vtree_operations/rollback.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/rollback.c
gcc -o build/vtree_operations/split.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_operations/split.c
gcc -o build/vtree_search/auto.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_search/auto.c
gcc -o build/vtree_search/search.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_search/search.c
gcc -o build/vtree_search/state.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_search/state.c
gcc -o build/vtrees/vtree.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/vtree.c
gcc -o build/vtrees/compare.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/compare.c
gcc -o build/vtrees/edit.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/edit.c
gcc -o build/vtrees/io.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/io.c
gcc -o build/vtrees/maps.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/maps.c
gcc -o build/vtrees/moves.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/moves.c
gcc -o build/vtrees/static.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtrees/static.c
gcc -o build/sdds/io.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/io.c
gcc -o build/sdds/apply.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/apply.c
gcc -o build/sdds/bits.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/bits.c
gcc -o build/sdds/cardinality.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/cardinality.c
gcc -o build/sdds/copy.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/copy.c
gcc -o build/sdds/count.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/count.c
gcc -o build/sdds/condition.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/condition.c
gcc -o build/sdds/essential_vars.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/essential_vars.c
gcc -o build/sdds/exists_multiple.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/exists_multiple.c
gcc -o build/sdds/exists_multiple_static.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/exists_multiple_static.c
gcc -o build/sdds/exists.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/exists.c
gcc -o build/sdds/forall.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/forall.c
gcc -o build/sdds/rename_vars.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/rename_vars.c
gcc -o build/sdds/model_count.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/model_count.c
gcc -o build/sdds/size.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/size.c
gcc -o build/sdds/wmc.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/sdds/wmc.c
gcc -o build/vtree_fragments/construction.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_fragments/construction.c
gcc -o build/vtree_fragments/moves.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_fragments/moves.c
gcc -o build/vtree_fragments/operations.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -fPIC -Iinclude -Isrc src/vtree_fragments/operations.c
gcc -o build/version.os -c -std=c99 -Wall -O2 -finline-functions -DNDEBUG -DSDD_VERSION=\"2.0\" -DSDD_DATE=\"June\ 27,\ 2022\" -fPIC -Iinclude -Isrc src/version.c
gcc -o build/libsdd.dylib -dynamiclib build/util.os build/verify.os build/fnf/io.os build/manager/copy.os build/manager/manager.os build/manager/interface.os build/manager/stats.os build/manager/variables.os build/vtree_operations/cartesian_product.os build/vtree_operations/dissect.os build/vtree_operations/limits.os build/vtree_operations/op_left_rotate.os build/vtree_operations/op_right_rotate.os build/vtree_operations/op_swap.os build/vtree_operations/rollback.os build/vtree_operations/split.os build/vtree_search/auto.os build/vtree_search/search.os build/vtree_search/state.os build/basic/computed.os build/basic/count_and_size.os build/basic/gc.os build/basic/hash.os build/basic/memory.os build/basic/multiply.os build/basic/nodes.os build/basic/partitions.os build/basic/references.os build/basic/replace.os build/basic/shadows.os build/basic/sort.os build/vtrees/vtree.os build/vtrees/compare.os build/vtrees/edit.os build/vtrees/io.os build/vtrees/maps.os build/vtrees/moves.os build/vtrees/static.os build/sdds/io.os build/sdds/apply.os build/sdds/bits.os build/sdds/cardinality.os build/sdds/copy.os build/sdds/count.os build/sdds/condition.os build/sdds/essential_vars.os build/sdds/exists_multiple.os build/sdds/exists_multiple_static.os build/sdds/exists.os build/sdds/forall.os build/sdds/rename_vars.os build/sdds/model_count.os build/sdds/size.os build/sdds/wmc.os build/vtree_fragments/construction.os build/vtree_fragments/moves.os build/vtree_fragments/operations.os build/version.os